/*

When you have added your code where it says
    // your code here
The program should generate a random integer in the interval 1-10
(including both 1 and 10).

The user will run the program guessing what the computer generates
using the command line argument.

If the user guessed the number generated by the program
the program outputs "Well done!"

Otherwise the program outputs: "No luck, play once more!"
meaning that the user can run the program once more

*/

import java.lang.Math;

public class E2{

	public static void main(String[] args) {
		int programGuess =(int)((Math.random()*10) + 1);
		int userSays = Integer.parseInt(args[0]);
		String message = "No luck, play once more!";

		if (userSays == programGuess)
		{
			message = "Well done!";
		}

		System.out.println(message);
	}
}
